#!/usr/bin/env python3
"""
ralph41 task 41.13: Figure S8C — biome comparison bar chart
============================================================

Produces a compact bar chart of Adjusted Rand Index (ARI) between the
HDBSCAN functional-biome partition and four alternative partition
schemes (Longhurst provinces, Longhurst biomes, ocean basins,
latitude quartile). Normalized Mutual Information (NMI) is overlaid
as a secondary set of bars.

Provenance
----------
- Input:  source_data/ralph41/biome_comparison.tsv
- Output: figures/FigureS8C_biome_comparison_{TIMESTAMP}.pdf
          figures/FigureS8C_biome_comparison_{TIMESTAMP}.svg

Data integrity
--------------
Reads only the authoritative biome_comparison.tsv generated by
scripts/ralph41/task_41_13.py. No numerical values are computed in
this figure script; it only plots what is already in the TSV.
"""

from __future__ import annotations

import csv
import datetime as _dt
import os
import sys
from pathlib import Path

import matplotlib as mpl

mpl.use("Agg")
import matplotlib.pyplot as plt

# Make palette import path available
WORKTREE = Path("/media/drn2/External/TARA-Oceans/MANUSCRIPT/.wt41/c3")
sys.path.insert(0, str(WORKTREE / "figures"))
from palette import OCEAN_BLUE, COASTAL_BLUE, DESERT_TAN, SAVANNA  # type: ignore

# ----------------------------------------------------------------------
# Matplotlib publication settings (per FIGURE_PROTOCOL.md)
# ----------------------------------------------------------------------
mpl.rcParams["pdf.fonttype"] = 42
mpl.rcParams["ps.fonttype"] = 42
mpl.rcParams["svg.fonttype"] = "none"
mpl.rcParams["font.family"] = "sans-serif"
mpl.rcParams["font.sans-serif"] = ["Arial", "Helvetica", "DejaVu Sans"]
mpl.rcParams["font.size"] = 6
mpl.rcParams["axes.labelsize"] = 6
mpl.rcParams["axes.titlesize"] = 6
mpl.rcParams["xtick.labelsize"] = 6
mpl.rcParams["ytick.labelsize"] = 6
mpl.rcParams["legend.fontsize"] = 6
mpl.rcParams["axes.linewidth"] = 0.25
mpl.rcParams["xtick.major.width"] = 0.25
mpl.rcParams["ytick.major.width"] = 0.25
mpl.rcParams["xtick.major.size"] = 2
mpl.rcParams["ytick.major.size"] = 2
mpl.rcParams["axes.labelpad"] = 1
mpl.rcParams["xtick.major.pad"] = 1
mpl.rcParams["ytick.major.pad"] = 1

# ----------------------------------------------------------------------
# Paths
# ----------------------------------------------------------------------
INPUT_TSV = WORKTREE / "source_data/ralph41/biome_comparison.tsv"
FIGURES_DIR = WORKTREE / "figures"
TIMESTAMP = _dt.datetime.now().strftime("%Y%m%d_%H%M%S")
OUT_STEM = FIGURES_DIR / f"FigureS8C_biome_comparison_{TIMESTAMP}"
PROVENANCE_MD = FIGURES_DIR / f"FigureS8C_biome_comparison_{TIMESTAMP}.md"

# ----------------------------------------------------------------------
# Read data
# ----------------------------------------------------------------------
if not INPUT_TSV.exists():
    sys.exit(f"ERROR: required input missing: {INPUT_TSV}")

rows = []
header_lines = []
with INPUT_TSV.open("r", newline="") as fh:
    reader = csv.reader(fh, delimiter="\t")
    columns = None
    for raw in reader:
        if not raw:
            continue
        if raw[0].startswith("#"):
            header_lines.append("\t".join(raw))
            continue
        if columns is None:
            columns = raw
            continue
        rows.append(dict(zip(columns, raw)))

# Fixed display order: Longhurst province first, latitude quartile last
display_order = [
    "longhurst_province",
    "longhurst_biome",
    "ocean_basin",
    "latitude_quartile",
]
display_labels = {
    "longhurst_province": "Longhurst\nprovinces",
    "longhurst_biome": "Longhurst\nbiomes",
    "ocean_basin": "Ocean\nbasin",
    "latitude_quartile": "Latitude\nquartile",
}
by_name = {r["scheme"]: r for r in rows}
ari_primary = [float(by_name[k]["ari_primary"]) for k in display_order]
nmi_primary = [float(by_name[k]["nmi_primary"]) for k in display_order]
ari_withnoise = [float(by_name[k]["ari_withnoise"]) for k in display_order]
nmi_withnoise = [float(by_name[k]["nmi_withnoise"]) for k in display_order]
n_cat = [int(by_name[k]["n_categories"]) for k in display_order]

# ----------------------------------------------------------------------
# Figure: two-panel (ARI, NMI). Single column ~3.5 in wide.
# ----------------------------------------------------------------------
fig, (ax_ari, ax_nmi) = plt.subplots(
    1, 2, figsize=(4.5, 2.2), layout="constrained"
)

x = list(range(len(display_order)))
bar_width = 0.35
x_primary = [xi - bar_width / 2 for xi in x]
x_with = [xi + bar_width / 2 for xi in x]

ari_color = OCEAN_BLUE
ari_alt_color = COASTAL_BLUE
nmi_color = SAVANNA
nmi_alt_color = DESERT_TAN

ax_ari.bar(
    x_primary,
    ari_primary,
    width=bar_width,
    color=ari_color,
    edgecolor="black",
    linewidth=0.25,
    label="noise excluded",
)
ax_ari.bar(
    x_with,
    ari_withnoise,
    width=bar_width,
    color=ari_alt_color,
    edgecolor="black",
    linewidth=0.25,
    label="noise included",
)

ax_nmi.bar(
    x_primary,
    nmi_primary,
    width=bar_width,
    color=nmi_color,
    edgecolor="black",
    linewidth=0.25,
    label="noise excluded",
)
ax_nmi.bar(
    x_with,
    nmi_withnoise,
    width=bar_width,
    color=nmi_alt_color,
    edgecolor="black",
    linewidth=0.25,
    label="noise included",
)

# Longhurst-province value annotations above the bars
for i, (v_p, v_w) in enumerate(zip(ari_primary, ari_withnoise)):
    ax_ari.text(
        x_primary[i],
        v_p + 0.015,
        f"{v_p:.2f}",
        ha="center",
        va="bottom",
        fontsize=5,
    )
for i, (v_p, v_w) in enumerate(zip(nmi_primary, nmi_withnoise)):
    ax_nmi.text(
        x_primary[i],
        v_p + 0.015,
        f"{v_p:.2f}",
        ha="center",
        va="bottom",
        fontsize=5,
    )

for ax in (ax_ari, ax_nmi):
    ax.set_xticks(x)
    ax.set_xticklabels(
        [display_labels[k] for k in display_order], fontsize=5.5, ha="center"
    )
    ax.set_xlim(-0.55, len(display_order) - 0.45)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.tick_params(axis="x", length=0)
    ax.set_ylim(0, 0.85)

ax_ari.set_ylabel("ARI vs HDBSCAN biomes")
ax_nmi.set_ylabel("NMI vs HDBSCAN biomes")
ax_ari.set_title("A  Adjusted Rand Index", loc="left", pad=2, fontsize=6)
ax_nmi.set_title("B  Normalized MI", loc="left", pad=2, fontsize=6)

# Legend below the figure (shared)
handles = [
    plt.Rectangle((0, 0), 1, 1, facecolor=ari_color, edgecolor="black", linewidth=0.25),
    plt.Rectangle((0, 0), 1, 1, facecolor=ari_alt_color, edgecolor="black", linewidth=0.25),
]
labels = ["noise excluded (primary)", "noise included (secondary)"]
fig.legend(
    handles,
    labels,
    loc="lower center",
    ncol=2,
    frameon=False,
    bbox_to_anchor=(0.5, -0.04),
    fontsize=5.5,
)

# ----------------------------------------------------------------------
# Save vector outputs
# ----------------------------------------------------------------------
FIGURES_DIR.mkdir(parents=True, exist_ok=True)
for fmt in ("pdf", "svg"):
    path = OUT_STEM.with_suffix(f".{fmt}")
    fig.savefig(
        path,
        format=fmt,
        dpi=600,
        bbox_inches="tight",
        transparent=True,
    )
    print(f"[task_41_13_figure] wrote {path}")

# Provenance sidecar
with PROVENANCE_MD.open("w") as fh:
    fh.write("# Provenance: FigureS8C biome comparison\n\n")
    fh.write(f"- Script: `{Path(__file__).resolve()}`\n")
    fh.write(f"- Input:  `{INPUT_TSV}`\n")
    fh.write(f"- Date:   {_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    fh.write(f"- Output PDF: `{OUT_STEM.with_suffix('.pdf')}`\n")
    fh.write(f"- Output SVG: `{OUT_STEM.with_suffix('.svg')}`\n\n")
    fh.write("## Numerical content (from TSV)\n\n")
    fh.write(
        "| Scheme | n_categories | ARI (primary) | NMI (primary) | "
        "ARI (with noise) | NMI (with noise) |\n"
    )
    fh.write("|---|---|---|---|---|---|\n")
    for k, nc, ap, np_, aw, nw in zip(
        display_order, n_cat, ari_primary, nmi_primary, ari_withnoise, nmi_withnoise
    ):
        fh.write(
            f"| {k} | {nc} | {ap:.4f} | {np_:.4f} | {aw:.4f} | {nw:.4f} |\n"
        )
print(f"[task_41_13_figure] wrote {PROVENANCE_MD}")
